#!/usr/bin/env python3
# coding: utf-8

"""
DateTime math from the terminal.


$ ./dmath.py 19h30 + 135m
21:45:00
$ ./dmath.py 19h30 + 235m
23:25:00
$ ./dmath.py 19h30 + 335m
01:05:00 D+1

"""

import sys
import operator
from datetime import datetime, date, time, timedelta


def parse_args():
    assert len(sys.argv) == 4

    start, op, delta = sys.argv[1:]

    assert len(start) == 5 and start[2] == 'h'  # 19h30
    assert op in '+', '-'
    assert delta.endswith('m')   # currently just minutes

    dt = datetime.combine(
        date.today(),
        time(*(int(x) for x in start.split('h')))
    )
    op = {'+': operator.add, '-': operator.sub}[op]
    delta = timedelta(seconds=60*int(delta.rstrip('m')))
    return dt, op, delta


def diff_days(result):
    _days = (result.date() - start.date()).days

    if _days > 0:
        return "D+%s" % abs(_days)
    elif _days < 0:
        return "D-%s" % abs(_days)
    return ""


if __name__ == "__main__":
    start, op, delta = parse_args()
    result = op(start, delta)
    D = diff_days(result)

    print(result.time(), D)
