#!/usr/bin/env python

"""
Very simple rss reader
"""

import feedparser


FEEDS = [
    ("Coding Horror", "http://feeds.feedburner.com/codinghorror"),
    ("Forgotten Labs", "http://www.forgottenlabs.com/feed/"),
    ("Seth Godin", "http://feeds.feedblitz.com/SethsBlog"),
]


def parse_feed(url):
    items = feedparser.parse(url)["items"]
    return [{
        "title": item["title"],
        "link": item["link"].split("utm_source")[0],
        "date": item["published"]
    } for item in items[:3]]


def print_item(item):
    print item["date"][:10].ljust(10), '//',
    print item["title"][:30].ljust(30), '//',
    print item["link"]


def print_feed(feed):
    print "\n"
    print feed[0]
    print "="*len(feed[0])

    for item in parse_feed(feed[1]):
        print_item(item)


if __name__ == '__main__':
    for feed in FEEDS:
        print_feed(feed)
